/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;

import Business.Agent.Agent;
import Business.Customer.Customer;
import Interface.CustomerWorkArea.*;
import Business.Enterprice.Enterprise;
import Business.Network.Network;
import Business.StockTrading;
import Business.User.UserAccount;
import Interface.AgentWorkArea.AgentWorkAreaJPanel;
import Interface.EnterpriseAdminRole.EnterpriseAdmin;
import Interface.SystemAdminWorkArea.SystemAdminWorkAreaJPanel;
import Utility.Constant.UserType;
import Utility.DB4OUtil;
import java.awt.CardLayout;
import java.awt.Color;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author Waqar
 */
public class mainJFrame extends javax.swing.JFrame {

    StockTrading stockInstance;
    private DB4OUtil dB4OUtil = DB4OUtil.getInstance();

    /**
     * Creates new form mainJFrame
     */
    public mainJFrame() {
        initComponents();
        
        this.stockInstance = dB4OUtil.retrieveSystem();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        buttonLogout = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        lblSystemAdmin2 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        enterpriseAdminButton = new javax.swing.JButton();
        jLabel42 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        textFieldUserName = new javax.swing.JTextField();
        textFieldPassword = new javax.swing.JPasswordField();
        buttonLogin = new javax.swing.JButton();
        systemAdminButton = new javax.swing.JButton();
        AgentLoginButton = new javax.swing.JButton();
        UserLoginButton = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        exitLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        rightContainer = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);

        jPanel4.setBackground(new java.awt.Color(51, 153, 0));

        jLabel31.setFont(new java.awt.Font("Rockwell Condensed", 1, 24)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(255, 255, 255));
        jLabel31.setText("Stock Trading Application");

        buttonLogout.setText("Logout");
        buttonLogout.setEnabled(false);
        buttonLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLogoutActionPerformed(evt);
            }
        });

        jPanel3.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(153, 255, 153));
        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 86, 114, 0));

        lblSystemAdmin2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblSystemAdmin2MouseClicked(evt);
            }
        });
        jPanel3.add(lblSystemAdmin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, -1, -1));

        jLabel33.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jLabel33KeyPressed(evt);
            }
        });
        jPanel3.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 90, -1, -1));
        jPanel3.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 90, 74, -1));
        jPanel3.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 80, -1, -1));
        jPanel3.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, -1, -1));

        enterpriseAdminButton.setBackground(new java.awt.Color(153, 255, 153));
        enterpriseAdminButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        enterpriseAdminButton.setForeground(new java.awt.Color(51, 102, 0));
        enterpriseAdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons8_Administrator_Male_50px.png"))); // NOI18N
        enterpriseAdminButton.setText("Enterprise Admin");
        enterpriseAdminButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        enterpriseAdminButton.setBorderPainted(false);
        enterpriseAdminButton.setContentAreaFilled(false);
        enterpriseAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                enterpriseAdminButtonActionPerformed(evt);
            }
        });
        jPanel3.add(enterpriseAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 60, -1, -1));

        jLabel42.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jLabel42.setForeground(new java.awt.Color(51, 153, 0));
        jLabel42.setText("LOGIN AS-");
        jPanel3.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 40, -1, -1));
        jPanel3.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 40, -1, -1));
        jPanel3.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 40, -1, -1));

        textFieldUserName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldUserNameActionPerformed(evt);
            }
        });
        jPanel3.add(textFieldUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 118, -1));
        jPanel3.add(textFieldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 20, 118, -1));

        buttonLogin.setBackground(new java.awt.Color(153, 255, 153));
        buttonLogin.setForeground(new java.awt.Color(153, 255, 153));
        buttonLogin.setText("Login");
        buttonLogin.setContentAreaFilled(false);
        buttonLogin.setEnabled(false);
        buttonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonLoginActionPerformed(evt);
            }
        });
        jPanel3.add(buttonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, 100, -1));

        systemAdminButton.setBackground(new java.awt.Color(153, 255, 153));
        systemAdminButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        systemAdminButton.setForeground(new java.awt.Color(51, 102, 0));
        systemAdminButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons8_Admin_Settings_Male_50px_1.png"))); // NOI18N
        systemAdminButton.setText("System Admin");
        systemAdminButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        systemAdminButton.setBorderPainted(false);
        systemAdminButton.setContentAreaFilled(false);
        systemAdminButton.setSelected(true);
        systemAdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                systemAdminButtonMouseClicked(evt);
            }
        });
        systemAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                systemAdminButtonActionPerformed(evt);
            }
        });
        jPanel3.add(systemAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 60, -1, -1));

        AgentLoginButton.setBackground(new java.awt.Color(153, 255, 153));
        AgentLoginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        AgentLoginButton.setForeground(new java.awt.Color(51, 102, 0));
        AgentLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons8_Management_64px.png"))); // NOI18N
        AgentLoginButton.setText("Agent");
        AgentLoginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AgentLoginButton.setBorderPainted(false);
        AgentLoginButton.setContentAreaFilled(false);
        AgentLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgentLoginButtonActionPerformed(evt);
            }
        });
        jPanel3.add(AgentLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, -1, -1));

        UserLoginButton.setBackground(new java.awt.Color(153, 255, 153));
        UserLoginButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        UserLoginButton.setForeground(new java.awt.Color(51, 102, 0));
        UserLoginButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons8_Male_User_52px.png"))); // NOI18N
        UserLoginButton.setText("User");
        UserLoginButton.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        UserLoginButton.setBorderPainted(false);
        UserLoginButton.setContentAreaFilled(false);
        UserLoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLoginButtonActionPerformed(evt);
            }
        });
        jPanel3.add(UserLoginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(860, 60, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons8_Name_30px_1.png"))); // NOI18N
        jPanel3.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 10, -1, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons8_Password_30px_1.png"))); // NOI18N
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 10, -1, -1));

        exitLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons8_Cancel_25px.png"))); // NOI18N
        exitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitLabelMouseClicked(evt);
            }
        });
        exitLabel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                exitLabelKeyPressed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/icons8_Profit_48px.png"))); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addGap(0, 931, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel31)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(exitLabel)))
                .addGap(61, 61, 61))
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addGap(10, 10, 10))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exitLabel)
                            .addComponent(buttonLogout)
                            .addComponent(jLabel31))
                        .addGap(18, 18, 18)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jSplitPane1.setTopComponent(jPanel4);

        rightContainer.setLayout(new java.awt.CardLayout());
        jSplitPane1.setRightComponent(rightContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1135, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void systemAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_systemAdminButtonActionPerformed
        // TODO add your handling code here:
        boolean isPasswordFound = false;
        // Get user name
        String userName = this.textFieldUserName.getText();
        // Get Password
        char[] passwordCharArray = this.textFieldPassword.getPassword();
        String password = String.valueOf(passwordCharArray);

        if (userName.equals("Sys") && password.equals("Sys")) {
            isPasswordFound = true;
            SystemAdminWorkAreaJPanel sysAdminWorkArea = new SystemAdminWorkAreaJPanel(this.rightContainer, stockInstance);
            this.rightContainer.add(sysAdminWorkArea);
            CardLayout layout = (CardLayout) this.rightContainer.getLayout();
            layout.next(this.rightContainer);

            systemAdminButton.setEnabled(false);
            buttonLogout.setEnabled(true);
            textFieldUserName.setEnabled(false);
            textFieldPassword.setEnabled(false);
       
    }//GEN-LAST:event_systemAdminButtonActionPerformed
        else{
            JOptionPane.showMessageDialog(null, "Invalid Credentials");
            return;
        }
    }
    private void buttonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLoginActionPerformed

        boolean isPasswordFound = false;
        // Get user name
        String userName = this.textFieldUserName.getText();
        // Get Password
        char[] passwordCharArray = this.textFieldPassword.getPassword();
        String password = String.valueOf(passwordCharArray);

         if ( userName.equals("Sys") && password.equals("Sys")) {
            isPasswordFound = true;
            SystemAdminWorkAreaJPanel sysAdminWorkArea = new SystemAdminWorkAreaJPanel(this.rightContainer, this.stockInstance);
            this.rightContainer.add(sysAdminWorkArea);
            CardLayout layout = (CardLayout) this.rightContainer.getLayout();
            layout.next(this.rightContainer);

            buttonLogin.setEnabled(false);
            buttonLogout.setEnabled(true);
            textFieldUserName.setEnabled(false);
            textFieldPassword.setEnabled(false);

            /*  } else if (type == UserType.EnterpriseAdmin) {

            for (Network network : this.stockInstance.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserList()) {
                        if (userName.equals(userAccount.getUserName()) && password.equals(userAccount.getPassword())) {
                            isPasswordFound = true;
                            EnterpriseAdmin enterpriseAdmin = new EnterpriseAdmin(this.jPanel1, network, enterprise);
                            this.jPanel1.add(enterpriseAdmin);
                            CardLayout layout = (CardLayout) this.jPanel1.getLayout();
                            layout.next(this.jPanel1);

                            buttonLogin.setEnabled(false);
                            buttonLogout.setEnabled(true);
                            textFieldUserName.setEnabled(false);
                            textFieldPassword.setEnabled(false);

                        }

                    }
                }
            }
        } else if (type == UserType.Agent) {

            for (Network network : this.stockInstance.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    for (Agent agent : enterprise.getAgentDirectoryList().getAgentList()) {

                        UserAccount userAccount = agent.getUserAccount();
                        if (userName.equals(userAccount.getUserName()) && password.equals(userAccount.getPassword())) {
                            isPasswordFound = true;
                            AgentWorkAreaJPanel agentWorkArea = new AgentWorkAreaJPanel(this.jPanel1, network, enterprise, agent);
                            this.jPanel1.add(agentWorkArea);
                            CardLayout layout = (CardLayout) this.jPanel1.getLayout();
                            layout.next(this.jPanel1);

                            buttonLogin.setEnabled(false);
                            buttonLogout.setEnabled(true);
                            textFieldUserName.setEnabled(false);
                            textFieldPassword.setEnabled(false);

                        }

                    }
                }
            }
        } else if (type == UserType.Customer) {

            for (Network network : this.stockInstance.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    for (Agent agent : enterprise.getAgentDirectoryList().getAgentList()) {
                        for (Customer customer : agent.getCustomerDirectoryList().getCustomerList()) {

                            UserAccount userAccount = customer.getUserAccount();
                            if (userName.equals(userAccount.getUserName()) && password.equals(userAccount.getPassword())) {
                                isPasswordFound = true;

                                CustomerWorkAreaJPanel customerWorkArea = new CustomerWorkAreaJPanel(this.jPanel1, network, enterprise, agent, customer);
                                this.jPanel1.add(customerWorkArea);
                                CardLayout layout = (CardLayout) this.jPanel1.getLayout();
                                layout.next(this.jPanel1);

                                buttonLogin.setEnabled(false);
                                buttonLogout.setEnabled(true);
                                textFieldUserName.setEnabled(false);
                                textFieldPassword.setEnabled(false);

                            }
                        }

                    }
                }
            }
        }

        if (!isPasswordFound) {
            JOptionPane.showMessageDialog(null, "Password Not found!!");
        }
        */}
    }//GEN-LAST:event_buttonLoginActionPerformed
   // }
    private void enterpriseAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_enterpriseAdminButtonActionPerformed
        // TODO add your handling code here:

        boolean isPasswordFound = false;
        // Get user name
        String userName = this.textFieldUserName.getText();
        // Get Password
        char[] passwordCharArray = this.textFieldPassword.getPassword();
        String password = String.valueOf(passwordCharArray);

      
        for (Network network : this.stockInstance.getNetworkList()) {
            for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                for (UserAccount userAccount : enterprise.getUserAccountDirectory().getUserList()) {
                    if (userName.equals(userAccount.getUserName()) && password.equals(userAccount.getPassword())) {
                        isPasswordFound = true;
                        EnterpriseAdmin enterpriseAdmin = new EnterpriseAdmin(this.rightContainer, network, enterprise, this.stockInstance, userAccount);
                        this.rightContainer.add(enterpriseAdmin);
                        CardLayout layout = (CardLayout) this.rightContainer.getLayout();
                        layout.next(this.rightContainer);

                        buttonLogin.setEnabled(false);
                        buttonLogout.setEnabled(true);
                        textFieldUserName.setEnabled(false);
                        textFieldPassword.setEnabled(false);   
                }
               
        }
            }
        }
        if (!isPasswordFound) {
            JOptionPane.showMessageDialog(null, "Incorrect password or Id!!");
        }
    }//GEN-LAST:event_enterpriseAdminButtonActionPerformed

    private void jLabel33KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jLabel33KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel33KeyPressed

    private void lblSystemAdmin2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblSystemAdmin2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_lblSystemAdmin2MouseClicked

    private void buttonLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonLogoutActionPerformed

        buttonLogin.setEnabled(true);
        buttonLogout.setEnabled(false);
        textFieldUserName.setEnabled(true);
        textFieldPassword.setEnabled(true);

        textFieldUserName.setText("");
        textFieldPassword.setText("");

        this.rightContainer.removeAll();
        JPanel blankJP = new JPanel();
        rightContainer.add(blankJP);
        CardLayout cardLayoutObj = (CardLayout) rightContainer.getLayout();
        cardLayoutObj.next(rightContainer);

        dB4OUtil.storeSystem(stockInstance);
    }//GEN-LAST:event_buttonLogoutActionPerformed

    private void AgentLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgentLoginButtonActionPerformed
        // TODO add your handling code here:
        try{ 
        boolean isPasswordFound = false;
        // Get user name
        String userName = this.textFieldUserName.getText();
        // Get Password
        char[] passwordCharArray = this.textFieldPassword.getPassword();
        String password = String.valueOf(passwordCharArray);
        for (Network network : this.stockInstance.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    for (Agent agent : enterprise.getAgentDirectoryList().getAgentList()) {

                        UserAccount userAccount = agent.getUserAccount();
                        if (userName.equals(userAccount.getUserName()) && password.equals(userAccount.getPassword())) {
                            isPasswordFound = true;
                            AgentWorkAreaJPanel agentWorkArea = new AgentWorkAreaJPanel(this.rightContainer, network, enterprise, agent);
                            this.rightContainer.add(agentWorkArea);
                            CardLayout layout = (CardLayout) this.rightContainer.getLayout();
                            layout.next(this.rightContainer);

                            buttonLogin.setEnabled(false);
                            buttonLogout.setEnabled(true);
                            textFieldUserName.setEnabled(false);
                            textFieldPassword.setEnabled(false);

                        }
                  
                    }
                }
            }
        }
           catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Credentials");
            return;
        } 
    }//GEN-LAST:event_AgentLoginButtonActionPerformed

    private void UserLoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLoginButtonActionPerformed
        // TODO add your handling code here:
     try{
        boolean isPasswordFound = false;
        // Get user name
        String userName = this.textFieldUserName.getText();
        // Get Password
        char[] passwordCharArray = this.textFieldPassword.getPassword();
        String password = String.valueOf(passwordCharArray);
        
        
        
        for (Network network : this.stockInstance.getNetworkList()) {
                for (Enterprise enterprise : network.getEnterpriseDirectory().getEnterpriseList()) {
                    for (Agent agent : enterprise.getAgentDirectoryList().getAgentList()) {
                        for (Customer customer : agent.getCustomerDirectoryList().getCustomerList()) {

                            UserAccount userAccount = customer.getUserAccount();
                            if (userName.equals(userAccount.getUserName()) && password.equals(userAccount.getPassword())) {
                                isPasswordFound = true;

                                CustomerWorkAreaJPanel customerWorkArea = new CustomerWorkAreaJPanel(this.rightContainer, network, enterprise, agent, customer);
                                this.rightContainer.add(customerWorkArea);
                                CardLayout layout = (CardLayout) this.rightContainer.getLayout();
                                layout.next(this.rightContainer);

                                buttonLogin.setEnabled(false);
                                buttonLogout.setEnabled(true);
                                textFieldUserName.setEnabled(false);
                                textFieldPassword.setEnabled(false);

                            }
                        }

                    }
                }
        }
     
    }//GEN-LAST:event_UserLoginButtonActionPerformed
     catch(Exception e){
            JOptionPane.showMessageDialog(null, "Invalid Credentials");
            return;
        }
    }
    private void exitLabelKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_exitLabelKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_exitLabelKeyPressed

    private void exitLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitLabelMouseClicked
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_exitLabelMouseClicked

    private void textFieldUserNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldUserNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldUserNameActionPerformed

    private void systemAdminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_systemAdminButtonMouseClicked
        // TODO add your handling code here:
        enterpriseAdminButton.setBackground(new Color(3, 59, 90).brighter());
    }//GEN-LAST:event_systemAdminButtonMouseClicked

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(mainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new mainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AgentLoginButton;
    private javax.swing.JButton UserLoginButton;
    private javax.swing.JButton buttonLogin;
    private javax.swing.JButton buttonLogout;
    private javax.swing.JButton enterpriseAdminButton;
    private javax.swing.JLabel exitLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JLabel lblSystemAdmin2;
    private javax.swing.JPanel rightContainer;
    private javax.swing.JButton systemAdminButton;
    private javax.swing.JPasswordField textFieldPassword;
    private javax.swing.JTextField textFieldUserName;
    // End of variables declaration//GEN-END:variables
}
