/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.SystemAdminWorkArea;

import Business.StockTrading;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author Waqar
 */
public class SystemAdminWorkAreaJPanel extends javax.swing.JPanel {

    JPanel rightContainer;
    StockTrading stockInstance;

    /**
     * Creates new form SystemAdminWorkAreaJPanel
     */
    public SystemAdminWorkAreaJPanel(JPanel rightContainer, StockTrading stockInstance) {
        initComponents();
        this.rightContainer = rightContainer;
        this.stockInstance = stockInstance;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnManageNetwork = new javax.swing.JButton();
        btnManageEnterprise = new javax.swing.JButton();
        btnManageAdmin = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        btnManageNetwork.setBackground(new java.awt.Color(204, 255, 204));
        btnManageNetwork.setFont(new java.awt.Font("Segoe UI Emoji", 1, 11)); // NOI18N
        btnManageNetwork.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/SystemAdminWorkArea/icons8_Network_50px_1.png"))); // NOI18N
        btnManageNetwork.setText("CREATE NETWORK");
        btnManageNetwork.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnManageNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageNetworkActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageNetwork);
        btnManageNetwork.setBounds(380, 81, 240, 40);

        btnManageEnterprise.setBackground(new java.awt.Color(204, 255, 204));
        btnManageEnterprise.setFont(new java.awt.Font("Segoe UI Emoji", 1, 11)); // NOI18N
        btnManageEnterprise.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/SystemAdminWorkArea/icons8_Stacked_Organizational_Chart_Highlighted_First_Node_50px.png"))); // NOI18N
        btnManageEnterprise.setText("CREATE ENTERPRISE");
        btnManageEnterprise.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnManageEnterprise.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEnterpriseActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageEnterprise);
        btnManageEnterprise.setBounds(380, 140, 240, 40);

        btnManageAdmin.setBackground(new java.awt.Color(204, 255, 204));
        btnManageAdmin.setFont(new java.awt.Font("Segoe UI Emoji", 1, 11)); // NOI18N
        btnManageAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/SystemAdminWorkArea/icons8_Administrator_Male_52px.png"))); // NOI18N
        btnManageAdmin.setText("CREATE ENTERPRISE ADMIN");
        btnManageAdmin.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnManageAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageAdminActionPerformed(evt);
            }
        });
        jPanel1.add(btnManageAdmin);
        btnManageAdmin.setBounds(380, 200, 240, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/SystemAdminWorkArea/stock.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 810, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 806, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 806, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 497, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 497, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageNetworkActionPerformed
        // TODO add your handling code here:

        CreateNetwork createNetwork = new CreateNetwork(this.rightContainer, this.stockInstance);
        this.rightContainer.add(createNetwork);
        CardLayout layout = (CardLayout) this.rightContainer.getLayout();
        layout.next(this.rightContainer);
    }//GEN-LAST:event_btnManageNetworkActionPerformed

    private void btnManageEnterpriseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEnterpriseActionPerformed
        // TODO add your handling code here:

        CreateEnterprice createEnterprice = new CreateEnterprice(this.rightContainer, this.stockInstance);
        this.rightContainer.add(createEnterprice);
        CardLayout layout = (CardLayout) this.rightContainer.getLayout();
        layout.next(this.rightContainer);
    }//GEN-LAST:event_btnManageEnterpriseActionPerformed

    private void btnManageAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageAdminActionPerformed
        // TODO add your handling code here:

        EnterpriceCredentials obj = new EnterpriceCredentials(this.rightContainer, this.stockInstance);
        this.rightContainer.add(obj);
        CardLayout layout = (CardLayout) this.rightContainer.getLayout();
        layout.next(this.rightContainer);
    }//GEN-LAST:event_btnManageAdminActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageAdmin;
    private javax.swing.JButton btnManageEnterprise;
    private javax.swing.JButton btnManageNetwork;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
