/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerWorkArea;

import Business.Agent.Agent;
import Business.Customer.Customer;
import Business.Customer.PurchasedShares;
import Business.Enterprice.Enterprise;
import Business.Network.Network;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartFrame;
import org.jfree.chart.ChartRenderingInfo;
import org.jfree.chart.ChartUtilities;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.entity.StandardEntityCollection;
import org.jfree.chart.plot.CategoryPlot;
import org.jfree.chart.plot.PlotOrientation;
import org.jfree.data.category.DefaultCategoryDataset;

/**
 *
 * @author Waqar
 */
public class CustomerWorkAreaJPanel extends javax.swing.JPanel {

    Network network;
    Enterprise enterprise;
    Agent agent;
    JPanel rightContainer;
    Customer customer;
    Organization organization;

    /**
     * Creates new form AgentWorkAreaJPanel
     */
    public CustomerWorkAreaJPanel(JPanel rightContainer, Network network, Enterprise enterprise, Agent agent, Customer customer) {
        initComponents();

        this.labelEnterprise.setText(enterprise.getEnterpriseName());
        this.lableNetwork.setText(network.getName());
        this.labelAgent.setText(agent.getName());
        this.labelCustomer.setText(customer.getName());
        this.labelAmountAvailable.setText(String.valueOf(customer.getBalance()));

        this.rightContainer = rightContainer;
        this.network = network;
        this.enterprise = enterprise;
        this.agent = agent;
        this.customer = customer;

        this.populateTable();
       // this.populatePurchasedTable();
    }

    private void populateTable() {
        DefaultTableModel model = (DefaultTableModel) this.tableCompany.getModel();
        model.setRowCount(0);

        for (Organization organization : this.agent.getSelectedOrganizationDirectoryList().getOrganizationList()) {
            Object[] row = new Object[5];
            row[0] = organization.getCompnayType();
            row[1] = organization.getCompanyName();
            row[2] = organization.getTotalNoOfshares();
            row[3] = organization.getShareVale();
            row[4] = this.agent.getBrokeragePercent();

            model.addRow(row);
        }
    }

    private void populatePurchasedTable() {
        DefaultTableModel model = (DefaultTableModel) this.tablePurchasedCompany.getModel();
        model.setRowCount(0);
        int lblAmtTot = 0;

            for (PurchasedShares purchasedShares : this.customer.getPurchasedSharesDirectory().getPurchasedSharesList()) {
                Object[] row = new Object[4];
                row[0] = purchasedShares.getCompanyName();
                row[1] = purchasedShares.getNoPurchasedShares();
                row[2] = purchasedShares.getAtPrice();
                row[3] = purchasedShares.getTotal();

                model.addRow(row);
            lblAmtTot = lblAmtTot + purchasedShares.getTotal();
        }
            labelAmountAvailable.setText(String.valueOf(customer.getBalance() - lblAmtTot));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labelAgent = new javax.swing.JLabel();
        enterpriseLabel2 = new javax.swing.JLabel();
        enterpriseLabel = new javax.swing.JLabel();
        labelEnterprise = new javax.swing.JLabel();
        lableNetwork = new javax.swing.JLabel();
        enterpriseLabel1 = new javax.swing.JLabel();
        labelCustomer = new javax.swing.JLabel();
        enterpriseLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCompany = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablePurchasedCompany = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelAmountAvailable = new javax.swing.JLabel();
        textFieldPurchased = new javax.swing.JTextField();
        buttonPurchased = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        chartButton = new javax.swing.JButton();
        sellSharesButton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        sellSharesTextField = new javax.swing.JTextField();

        setBackground(new java.awt.Color(255, 255, 255));

        labelAgent.setText("<value>");

        enterpriseLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel2.setText("Agent:");

        enterpriseLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel.setText("EnterPrise :");

        labelEnterprise.setText("<value>");

        lableNetwork.setText("<value>");

        enterpriseLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel1.setText("Network");

        labelCustomer.setText("<value>");

        enterpriseLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        enterpriseLabel3.setText("Customer");

        tableCompany.setBackground(new java.awt.Color(204, 204, 255));
        tableCompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Company Type", "Company Name", "Available Shares", "Price Per Share"
            }
        ));
        jScrollPane1.setViewportView(tableCompany);

        jButton2.setText("<<Back");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        tablePurchasedCompany.setBackground(new java.awt.Color(204, 204, 255));
        tablePurchasedCompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Company Name", "No Purchased Shares", "At Price", "Total"
            }
        ));
        jScrollPane2.setViewportView(tablePurchasedCompany);

        jLabel1.setText("Available Companies");

        jLabel2.setText("Shares You Owe");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel3.setText("Available Amount:");

        labelAmountAvailable.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        labelAmountAvailable.setText("NA");

        textFieldPurchased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldPurchasedActionPerformed(evt);
            }
        });

        buttonPurchased.setText("Purchase");
        buttonPurchased.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonPurchasedActionPerformed(evt);
            }
        });

        jLabel4.setText("No of shares:");

        chartButton.setText("Create Chart");
        chartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chartButtonActionPerformed(evt);
            }
        });

        sellSharesButton.setText("Sell Shares");
        sellSharesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sellSharesButtonActionPerformed(evt);
            }
        });

        jButton1.setText("Download File");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(lableNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(labelEnterprise, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(enterpriseLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(labelAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(enterpriseLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(labelCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(labelAmountAvailable, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(312, 312, 312)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(textFieldPurchased, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(35, 35, 35)
                        .addComponent(buttonPurchased, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 990, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jButton2)
                        .addGap(59, 59, 59)
                        .addComponent(sellSharesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(sellSharesButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80)
                        .addComponent(chartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(70, 70, 70)
                        .addComponent(jButton1)))
                .addGap(36, 36, 36))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lableNetwork))
                    .addComponent(enterpriseLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(labelEnterprise))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(enterpriseLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelAgent))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(enterpriseLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(labelCustomer)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(labelAmountAvailable))
                .addGap(11, 11, 11)
                .addComponent(jLabel1)
                .addGap(6, 6, 6)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel4))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(textFieldPurchased, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(buttonPurchased))
                .addGap(10, 10, 10)
                .addComponent(jLabel2)
                .addGap(4, 4, 4)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(sellSharesButton)
                                .addComponent(sellSharesTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chartButton)
                                .addComponent(jButton1)))))
                .addContainerGap(15, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        rightContainer.remove(this);
        Component[] componentArray = rightContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.previous(rightContainer);        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void textFieldPurchasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldPurchasedActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldPurchasedActionPerformed

    private void buttonPurchasedActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonPurchasedActionPerformed
        // TODO add your handling code here:

        int selectedRow = tableCompany.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to purchase ?", "Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                Organization organization = this.agent.getSelectedOrganizationDirectoryList().getOrganizationList().get(selectedRow);

                int noOfsahresPurshased = Integer.valueOf(textFieldPurchased.getText());

                System.out.println("Outside if");
                System.out.println(organization.getTotalNoOfshares());
                
                if (organization.getTotalNoOfshares() >= noOfsahresPurshased && customer.getBalance() >= noOfsahresPurshased * organization.getShareVale()) {

                    System.out.println("Inside if");
                    PurchasedShares purchasedShares = this.customer.getPurchasedSharesDirectory().createAndAddPurchasedShares();
                    purchasedShares.setCompanyName(organization.getCompanyName());
                    purchasedShares.setNoPurchasedShares(noOfsahresPurshased);
                    purchasedShares.setAtPrice(organization.getShareVale());
                    purchasedShares.setTotal(noOfsahresPurshased * organization.getShareVale());
  
                    organization.setTotalNoOfshares(organization.getTotalNoOfshares() - noOfsahresPurshased);

                    this.populateTable();
                    this.populatePurchasedTable();

                } else {
                    JOptionPane.showMessageDialog(null, "Please Enter Valid No. !!");

                }

            }
        } else {
            JOptionPane.showMessageDialog(null, "Please select a Row!!");
        }


    }//GEN-LAST:event_buttonPurchasedActionPerformed

    private void chartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chartButtonActionPerformed
        // TODO add your handling code here:
   
               DefaultCategoryDataset dataset = new DefaultCategoryDataset();
                for (PurchasedShares e : customer.getPurchasedSharesDirectory().getPurchasedSharesList()) {
                        dataset.setValue(e.getNoPurchasedShares(), "Total Price", e.getCompanyName());
                    
                }
            
        JFreeChart chart =  ChartFactory.createBarChart3D("Shares Report", "Company Name", "No of shares purchased", dataset, PlotOrientation.VERTICAL, false, true, false);
        chart.setBackgroundPaint(Color.GRAY);
        chart.getTitle().setPaint(Color.BLUE);
        CategoryPlot p = chart.getCategoryPlot();
        p.setRangeGridlinePaint(Color.BLACK);
        ChartFrame frame = new ChartFrame("Bar Chart for Customer", chart);
        frame.setVisible(true);
        frame.setSize(450, 350);

        try {
            final ChartRenderingInfo info = new ChartRenderingInfo(new StandardEntityCollection());
            final File file1 = new File("Customer_Report.png");
            ChartUtilities.saveChartAsPNG(file1, chart, 600, 400, info);

        } catch (Exception e) {

        }
    }//GEN-LAST:event_chartButtonActionPerformed

    private void sellSharesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sellSharesButtonActionPerformed
        // TODO add your handling code here:
        int selectedRow = tablePurchasedCompany.getSelectedRow();
        if (selectedRow >= 0) {
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to sell ?", "Warning", selectionButton);
            if (selectionResult == JOptionPane.YES_OPTION) {
                PurchasedShares purchasedShares = this.customer.getPurchasedSharesDirectory().getPurchasedSharesList().get(selectedRow);
             int noOfsahresPurshased = Integer.valueOf(textFieldPurchased.getText());

                if(purchasedShares.getNoPurchasedShares() >= noOfsahresPurshased){
                    purchasedShares = this.customer.getPurchasedSharesDirectory().sellPurchasedShares();
                    organization.setCompanyName(organization.getCompanyName());
                    organization.setTotalNoOfshares(organization.getTotalNoOfshares()+noOfsahresPurshased);
                    organization.setShareVale(organization.getShareVale());
                    //this.agent.setBrokeragePercent(this.agent.getSelectedOrganizationDirectoryList());
  
                       
                 purchasedShares.setNoPurchasedShares(noOfsahresPurshased);
                    
                }
            }
    }//GEN-LAST:event_sellSharesButtonActionPerformed
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        File file = new File("H:\\StockTradingApplication\\xyz.xls");

        try {
            FileWriter fw = new FileWriter(file);
            BufferedWriter bw = new BufferedWriter(fw);

            for (int j = 0; j < tablePurchasedCompany.getColumnCount(); j++) {
                bw.write(tablePurchasedCompany.getColumnName(j) + "\t");
            }
            bw.newLine();
            
            for (int i = 0; i < tablePurchasedCompany.getRowCount(); i++) {
                for (int j = 0; j < tablePurchasedCompany.getColumnCount(); j++) {
                    System.out.println(tablePurchasedCompany.getValueAt(i, j).toString());
                    bw.write(tablePurchasedCompany.getValueAt(i, j).toString() + "\t");
                }
                bw.newLine();
            }

            bw.close();
            fw.close();
        } catch (IOException ex) {
            Logger.getLogger(CustomerWorkAreaJPanel.class.getName()).log(Level.SEVERE, null, ex);
    }//GEN-LAST:event_jButton1ActionPerformed
        JOptionPane.showMessageDialog(null, "Report Downloaded Successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);

    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonPurchased;
    private javax.swing.JButton chartButton;
    private javax.swing.JLabel enterpriseLabel;
    private javax.swing.JLabel enterpriseLabel1;
    private javax.swing.JLabel enterpriseLabel2;
    private javax.swing.JLabel enterpriseLabel3;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelAgent;
    private javax.swing.JLabel labelAmountAvailable;
    private javax.swing.JLabel labelCustomer;
    private javax.swing.JLabel labelEnterprise;
    private javax.swing.JLabel lableNetwork;
    private javax.swing.JButton sellSharesButton;
    private javax.swing.JTextField sellSharesTextField;
    private javax.swing.JTable tableCompany;
    private javax.swing.JTable tablePurchasedCompany;
    private javax.swing.JTextField textFieldPurchased;
    // End of variables declaration//GEN-END:variables
}
