/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EnterpriseAdminRole;

import Business.Enterprice.Enterprise;
import Business.Organization.Organization;
import Utility.Validation;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Waqar
 */
public class CreateOrganizationJPanle extends javax.swing.JPanel {

    JPanel rightContainer;
    Enterprise enterPrise;

    /**
     * Creates new form ManageOrganizationJPanle
     */
    public CreateOrganizationJPanle(JPanel rightContainer, Enterprise enterPrise) {
        initComponents();

        this.rightContainer = rightContainer;
        this.enterPrise = enterPrise;
        this.populateTable();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel8 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableCompany4 = new javax.swing.JTable();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        textFieldCompnayType4 = new javax.swing.JTextField();
        jLabel26 = new javax.swing.JLabel();
        textFieldNumberOfShares3 = new javax.swing.JTextField();
        jLabel27 = new javax.swing.JLabel();
        textFieldFaceValue3 = new javax.swing.JTextField();
        textFieldValuePerShare3 = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        buttonBack4 = new javax.swing.JButton();
        buttonAddOrganization4 = new javax.swing.JButton();
        textFieldCompnayName3 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(null);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setLayout(null);

        tableCompany4.setBackground(new java.awt.Color(204, 204, 255));
        tableCompany4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Company Type", "Company Name", "Total Number of Shares", "Face Value", "Value per Share"
            }
        ));
        jScrollPane6.setViewportView(tableCompany4);

        jPanel8.add(jScrollPane6);
        jScrollPane6.setBounds(10, 70, 1143, 127);

        jLabel24.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel24.setText("Comapny Type:");
        jPanel8.add(jLabel24);
        jLabel24.setBounds(241, 231, 100, 17);

        jLabel25.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel25.setText("Company Name:");
        jPanel8.add(jLabel25);
        jLabel25.setBounds(241, 269, 104, 17);

        textFieldCompnayType4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCompnayType4ActionPerformed(evt);
            }
        });
        jPanel8.add(textFieldCompnayType4);
        textFieldCompnayType4.setBounds(412, 221, 129, 30);

        jLabel26.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel26.setText("Total Number of Shares:");
        jPanel8.add(jLabel26);
        jLabel26.setBounds(241, 307, 149, 17);

        textFieldNumberOfShares3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumberOfShares3ActionPerformed(evt);
            }
        });
        jPanel8.add(textFieldNumberOfShares3);
        textFieldNumberOfShares3.setBounds(412, 297, 129, 30);

        jLabel27.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel27.setText("Face Value:");
        jPanel8.add(jLabel27);
        jLabel27.setBounds(241, 345, 69, 17);

        textFieldFaceValue3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFaceValue3ActionPerformed(evt);
            }
        });
        jPanel8.add(textFieldFaceValue3);
        textFieldFaceValue3.setBounds(412, 335, 129, 30);
        jPanel8.add(textFieldValuePerShare3);
        textFieldValuePerShare3.setBounds(412, 373, 129, 30);

        jLabel28.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel28.setText("Share Per Value");
        jPanel8.add(jLabel28);
        jLabel28.setBounds(241, 383, 95, 17);

        buttonBack4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonBack4.setText("<<BACK");
        buttonBack4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBack4buttonBackActionPerformed(evt);
            }
        });
        jPanel8.add(buttonBack4);
        buttonBack4.setBounds(61, 415, 95, 25);

        buttonAddOrganization4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        buttonAddOrganization4.setText("Add Organization");
        buttonAddOrganization4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddOrganization4buttonAddOrganizationActionPerformed(evt);
            }
        });
        jPanel8.add(buttonAddOrganization4);
        buttonAddOrganization4.setBounds(494, 415, 153, 25);

        textFieldCompnayName3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCompnayName3ActionPerformed(evt);
            }
        });
        jPanel8.add(textFieldCompnayName3);
        textFieldCompnayName3.setBounds(412, 259, 129, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Add Companies");
        jPanel8.add(jLabel1);
        jLabel1.setBounds(374, 35, 165, 17);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/EnterpriseAdminRole/stock.jpg"))); // NOI18N
        jPanel8.add(jLabel2);
        jLabel2.setBounds(-60, 0, 780, 460);

        add(jPanel8);
        jPanel8.setBounds(0, 0, 0, 460);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCompnayType4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCompnayType4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCompnayType4ActionPerformed

    private void textFieldNumberOfShares3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumberOfShares3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNumberOfShares3ActionPerformed

    private void textFieldFaceValue3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFaceValue3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFaceValue3ActionPerformed

    private void buttonBack4buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBack4buttonBackActionPerformed
        // TODO add your handling code here:
        rightContainer.remove(this);
        Component[] componentArray = rightContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.previous(rightContainer);
    }//GEN-LAST:event_buttonBack4buttonBackActionPerformed

    private void buttonAddOrganization4buttonAddOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddOrganization4buttonAddOrganizationActionPerformed
        // TODO add your handling code here:
       try{
           String companyType = textFieldCompnayType4.getText();
           String companyName = textFieldCompnayName3.getText();
           Integer totalNoOfShares = Integer.parseInt(textFieldNumberOfShares3.getText());
           Integer faceValue = Integer.parseInt(textFieldFaceValue3.getText());
           Integer shareValue = Integer.parseInt(textFieldValuePerShare3.getText());
           if(companyType.length() == 0 || companyName== null){
            JOptionPane.showMessageDialog(null, "Please complete all required fields");
        }
            else if(!Validation.isStringOnlyAlphabet(textFieldCompnayType4.getText())){
            JOptionPane.showMessageDialog(null, "Please enter a valid comapany type");    
        }
              else if(!Validation.isStringOnlyAlphabet(textFieldCompnayName3.getText())){
            JOptionPane.showMessageDialog(null, "Please enter a valid company name");    
        }
            else if(!Validation.validateTextFieldsForAmount(textFieldNumberOfShares3)){
            JOptionPane.showMessageDialog(null, "Please enter valid amount ");
        }
            else if(!Validation.validateTextFieldsForAmount(textFieldFaceValue3)){
            JOptionPane.showMessageDialog(null, "Please enter valid amount ");
        }
           else if(!Validation.validateTextFieldsForAmount(textFieldValuePerShare3)){
            JOptionPane.showMessageDialog(null, "Please enter valid amount ");
        }
         
           else{
            Organization obj = this.enterPrise.getOrganizationDirectoryList().createAndAddOrganization();
            obj.setCompnayType(this.textFieldCompnayType4.getText());
            obj.setCompanyName(this.textFieldCompnayName3.getText());
            obj.setTotalNoOfshares(Integer.parseInt(this.textFieldNumberOfShares3.getText()));
            obj.setFaceValue(Integer.parseInt(this.textFieldFaceValue3.getText()));
            obj.setShareVale(Integer.parseInt(this.textFieldValuePerShare3.getText()));
            this.populateTable();}}
       catch(NumberFormatException e){
               JOptionPane.showMessageDialog(null, "Please enter valid inputs","Incorrect Input", JOptionPane.WARNING_MESSAGE);

       }
    }//GEN-LAST:event_buttonAddOrganization4buttonAddOrganizationActionPerformed

    private void textFieldCompnayName3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCompnayName3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCompnayName3ActionPerformed

    private void populateTable() {
        if (this.enterPrise.getOrganizationDirectoryList() != null) {

            DefaultTableModel model = (DefaultTableModel) this.tableCompany4.getModel();
            model.setRowCount(0);
            for (Organization organization : this.enterPrise.getOrganizationDirectoryList().getOrganizationList()) {
                Object[] row = new Object[5];
                row[0] = organization.getCompnayType();
                row[1] = organization.getCompanyName();
                row[2] = organization.getTotalNoOfshares();
                row[3] = organization.getFaceValue();
                row[4] = organization.getShareVale();
                model.addRow(row);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddOrganization4;
    private javax.swing.JButton buttonBack4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JTable tableCompany4;
    private javax.swing.JTextField textFieldCompnayName3;
    private javax.swing.JTextField textFieldCompnayType4;
    private javax.swing.JTextField textFieldFaceValue3;
    private javax.swing.JTextField textFieldNumberOfShares3;
    private javax.swing.JTextField textFieldValuePerShare3;
    // End of variables declaration//GEN-END:variables
}
