/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.EnterpriseAdminRole;

import Business.Enterprice.Enterprise;
import Business.Organization.Organization;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Waqar
 */
public class CreateOrganizationJPanle extends javax.swing.JPanel {

    JPanel rightContainer;
    Enterprise enterPrise;

    /**
     * Creates new form ManageOrganizationJPanle
     */
    public CreateOrganizationJPanle(JPanel rightContainer, Enterprise enterPrise) {
        initComponents();

        this.rightContainer = rightContainer;
        this.enterPrise = enterPrise;
        this.populateTable();
    }

    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableCompany = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        textFieldCompnayType = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        textFieldNumberOfShares = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        textFieldFaceValue = new javax.swing.JTextField();
        textFieldValuePerShare = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        buttonBack1 = new javax.swing.JButton();
        buttonAddOrganization1 = new javax.swing.JButton();
        textFieldCompnayName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setLayout(null);

        tableCompany.setBackground(new java.awt.Color(204, 204, 255));
        tableCompany.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Company Type", "Company Name", "Total Number of Shares", "Face Value", "Value per Share"
            }
        ));
        jScrollPane2.setViewportView(tableCompany);

        jPanel4.add(jScrollPane2);
        jScrollPane2.setBounds(10, 40, 930, 127);

        jLabel7.setText("Comapny Type:");
        jPanel4.add(jLabel7);
        jLabel7.setBounds(241, 208, 76, 14);

        jLabel8.setText("Company Name:");
        jPanel4.add(jLabel8);
        jLabel8.setBounds(241, 246, 79, 14);

        textFieldCompnayType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCompnayTypeActionPerformed(evt);
            }
        });
        jPanel4.add(textFieldCompnayType);
        textFieldCompnayType.setBounds(380, 205, 129, 20);

        jLabel9.setText("Total Number of Shares:");
        jPanel4.add(jLabel9);
        jLabel9.setBounds(241, 284, 117, 14);

        textFieldNumberOfShares.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldNumberOfSharesActionPerformed(evt);
            }
        });
        jPanel4.add(textFieldNumberOfShares);
        textFieldNumberOfShares.setBounds(380, 281, 129, 20);

        jLabel10.setText("Face Value:");
        jPanel4.add(jLabel10);
        jLabel10.setBounds(241, 322, 56, 14);

        textFieldFaceValue.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldFaceValueActionPerformed(evt);
            }
        });
        jPanel4.add(textFieldFaceValue);
        textFieldFaceValue.setBounds(380, 319, 129, 20);
        jPanel4.add(textFieldValuePerShare);
        textFieldValuePerShare.setBounds(380, 357, 129, 20);

        jLabel11.setText("Share Per Value");
        jPanel4.add(jLabel11);
        jLabel11.setBounds(241, 360, 76, 14);

        buttonBack1.setText("<<BACK");
        buttonBack1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonBackActionPerformed(evt);
            }
        });
        jPanel4.add(buttonBack1);
        buttonBack1.setBounds(61, 389, 75, 23);

        buttonAddOrganization1.setText("Add Organization");
        buttonAddOrganization1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddOrganizationActionPerformed(evt);
            }
        });
        jPanel4.add(buttonAddOrganization1);
        buttonAddOrganization1.setBounds(474, 389, 150, 23);

        textFieldCompnayName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldCompnayNameActionPerformed(evt);
            }
        });
        jPanel4.add(textFieldCompnayName);
        textFieldCompnayName.setBounds(380, 243, 129, 20);

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Interface/EnterpriseAdminRole/stock.jpg"))); // NOI18N
        jPanel4.add(jLabel1);
        jLabel1.setBounds(-22, 0, 790, 490);

        add(jPanel4);
        jPanel4.setBounds(20, 0, 1369, 432);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldCompnayNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCompnayNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCompnayNameActionPerformed

    private void buttonAddOrganizationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddOrganizationActionPerformed
        // TODO add your handling code here:
    /*   if(textFieldCompnayName.getText().isEmpty() || textFieldCompnayType.getText().isEmpty() || textFieldFaceValue.getText().isEmpty() || textFieldNumberOfShares.getText().isEmpty() || textFieldValuePerShare.getText().isEmpty()){
            JOptionPane.showMessageDialog(null, "Please enter valid inputs");
         }
       else{ */
        Organization obj = this.enterPrise.getOrganizationDirectoryList().createAndAddOrganization();
        obj.setCompnayType(this.textFieldCompnayType.getText());
        obj.setCompanyName(this.textFieldCompnayName.getText());
        obj.setTotalNoOfshares(Integer.parseInt(this.textFieldNumberOfShares.getText()));
        obj.setFaceValue(Integer.parseInt(this.textFieldFaceValue.getText()));
        obj.setShareVale(Integer.parseInt(this.textFieldValuePerShare.getText()));
        this.populateTable();
    //}
    }//GEN-LAST:event_buttonAddOrganizationActionPerformed

    private void buttonBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonBackActionPerformed
        // TODO add your handling code here:
        rightContainer.remove(this);
        Component[] componentArray = rightContainer.getComponents();
        Component component = componentArray[componentArray.length - 1];
        CardLayout layout = (CardLayout) rightContainer.getLayout();
        layout.previous(rightContainer);

    }//GEN-LAST:event_buttonBackActionPerformed

    private void textFieldFaceValueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldFaceValueActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldFaceValueActionPerformed

    private void textFieldNumberOfSharesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldNumberOfSharesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldNumberOfSharesActionPerformed

    private void textFieldCompnayTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldCompnayTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldCompnayTypeActionPerformed

    private void populateTable() {
        if (this.enterPrise.getOrganizationDirectoryList() != null) {

            DefaultTableModel model = (DefaultTableModel) this.tableCompany.getModel();
            model.setRowCount(0);
            for (Organization organization : this.enterPrise.getOrganizationDirectoryList().getOrganizationList()) {
                Object[] row = new Object[5];
                row[0] = organization.getCompnayType();
                row[1] = organization.getCompanyName();
                row[2] = organization.getTotalNoOfshares();
                row[3] = organization.getFaceValue();
                row[4] = organization.getShareVale();
                model.addRow(row);
            }
        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddOrganization1;
    private javax.swing.JButton buttonBack1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tableCompany;
    private javax.swing.JTextField textFieldCompnayName;
    private javax.swing.JTextField textFieldCompnayType;
    private javax.swing.JTextField textFieldFaceValue;
    private javax.swing.JTextField textFieldNumberOfShares;
    private javax.swing.JTextField textFieldValuePerShare;
    // End of variables declaration//GEN-END:variables
}
